package logicbuild2;
public class firstFrame extends javax.swing.JFrame {

    public String [] jMealMenu = {
    /*Item 1: */ "Jmeal",
    /*Item 2: */ "JRice",
    /*Item 3: */ "JDrinks",
    };
    
    public firstFrame() {
        initComponents();
    }
    
//My Passable Values

public String firstVal, secondVal;
    
    public String valOfFirst (String firstVal){
        // returns Jmeal as the first value
            firstVal = jMealMenu[0];
            System.out.println(firstVal);
        return firstVal;
    }
    public String valOfSecond (String secondVal){
        // returns JRice as the second Value
            secondVal = jMealMenu[0];
            System.out.println(secondVal);
        return secondVal;
    }    
    
    
//My Pass Method    
    
    public void passFValToNext(){
        System.out.println("Passed: " + jMealMenu[0] + ", to the next Frame");
    }    
    public String passFValToSecond(String firstVal){
        //assign that firstVal is, (firstVal = JMeal)
            firstVal = jMealMenu[0];
            System.out.println(firstVal);
        //Call second frame
            secondFrame second = new secondFrame();
        //Then put the value into the parameter you set in the second frame;
            second.recieveAndGet(firstVal);
        return firstVal;    
    }        
    
    public void showLBar (){
        loadBar showLoad = new loadBar();
        showLoad.setVisible(true);
    }
    
    
//My Methods shortcuts
    
    public void showSecond(){
        secondFrame second = new secondFrame();
        second.setVisible(true);
    }
    public void showTable(){
        tableFrame table = new tableFrame();
        table.setVisible(true);
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        secondValue = new javax.swing.JButton();
        showSecond = new javax.swing.JButton();
        passValue = new javax.swing.JButton();
        firstValue = new javax.swing.JButton();
        showTable = new javax.swing.JButton();
        showValButton = new javax.swing.JButton();

        jLabel2.setText("jLabel2");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        secondValue.setText("Button With Value 2");
        secondValue.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                secondValueActionPerformed(evt);
            }
        });
        getContentPane().add(secondValue, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 40, 296, -1));

        showSecond.setText("Show Second Frame");
        showSecond.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                showSecondActionPerformed(evt);
            }
        });
        getContentPane().add(showSecond, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 80, -1, -1));

        passValue.setText("Pass to Table");
        passValue.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                passValueActionPerformed(evt);
            }
        });
        getContentPane().add(passValue, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 80, 141, -1));

        firstValue.setText("Button With Value 1");
        firstValue.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                firstValueActionPerformed(evt);
            }
        });
        getContentPane().add(firstValue, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 296, -1));

        showTable.setText("Show Table");
        showTable.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                showTableActionPerformed(evt);
            }
        });
        getContentPane().add(showTable, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 150, 296, -1));

        showValButton.setText("Show Value of the pressed button");
        showValButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                showValButtonActionPerformed(evt);
            }
        });
        getContentPane().add(showValButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 120, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void showTableActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_showTableActionPerformed
        // TODO add your handling code here:
        if(evt.getSource() == showTable){showTable();}
    }//GEN-LAST:event_showTableActionPerformed

    private void showSecondActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_showSecondActionPerformed
        // TODO add your handling code here:
        if(evt.getSource() == showSecond){
            showLBar();
            dispose();
            
            showSecond();
            //passFValToNext();
        }
    }//GEN-LAST:event_showSecondActionPerformed

    private void firstValueActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_firstValueActionPerformed
        // TODO add your handling code here:
        if(evt.getSource() == firstValue){
            valOfFirst(jMealMenu[0]);
            passFValToSecond(jMealMenu[0]);
            //System.out.println(firstVal);
        }
    }//GEN-LAST:event_firstValueActionPerformed

    private void secondValueActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_secondValueActionPerformed
        // TODO add your handling code here:
        if(evt.getSource() == secondValue){
            valOfFirst(jMealMenu[1]);
            
        }
    }//GEN-LAST:event_secondValueActionPerformed

    private void passValueActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_passValueActionPerformed
        // TODO add your handling code here:
        if(evt.getSource() == passValue){
            passFValToNext();
        }
    }//GEN-LAST:event_passValueActionPerformed

    private void showValButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_showValButtonActionPerformed
        // TODO add your handling code here:
        if(evt.getSource() == showValButton){
            //valOfFirst(firstVal);
            passFValToSecond(firstVal);
        }
    }//GEN-LAST:event_showValButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(firstFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(firstFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(firstFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(firstFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new firstFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton firstValue;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JButton passValue;
    private javax.swing.JButton secondValue;
    private javax.swing.JButton showSecond;
    private javax.swing.JButton showTable;
    private javax.swing.JButton showValButton;
    // End of variables declaration//GEN-END:variables
}
